goog.provide('init');
init.initialize_db = (function init$initialize_db(conn){
var _ = datascript.core.transact_BANG_.cljs$core$IFn$_invoke$arity$2(conn,new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword("db","add","db/add",235286841),(1),new cljs.core.Keyword("navigator","history","navigator/history",744551073),cljs.core.list("campaigns")], null)], null));
var ___$1 = datascript.core.transact_BANG_.cljs$core$IFn$_invoke$arity$2(conn,entities.realms.data.interface$.example_realms);
var ___$2 = datascript.core.transact_BANG_.cljs$core$IFn$_invoke$arity$2(conn,entities.creatures.data.interface$.creature_races);
var ___$3 = datascript.core.transact_BANG_.cljs$core$IFn$_invoke$arity$2(conn,entities.rulesets.data.interface$.default_domains);
var ___$4 = datascript.core.transact_BANG_.cljs$core$IFn$_invoke$arity$2(conn,entities.rulesets.data.interface$.example_rulesets);
var ___$5 = datascript.core.transact_BANG_.cljs$core$IFn$_invoke$arity$2(conn,entities.actions.data.interface$.example_actions);
var ___$6 = datascript.core.transact_BANG_.cljs$core$IFn$_invoke$arity$2(conn,entities.resources.data.interface$.resource_properties);
var ___$7 = datascript.core.transact_BANG_.cljs$core$IFn$_invoke$arity$2(conn,(function (){var G__39615 = cljs.core.vec(cljs.core.map.cljs$core$IFn$_invoke$arity$2(cljs.core.first,(function (){var G__39616 = new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"find","find",496279456),new cljs.core.Symbol(null,"?e","?e",-1194391683,null),new cljs.core.Keyword(null,"where","where",-2044795965),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Symbol(null,"?e","?e",-1194391683,null),new cljs.core.Keyword(null,"entity-type","entity-type",-1957300125),"action"], null)], null);
var G__39617 = cljs.core.deref(conn);
return (datascript.core.q.cljs$core$IFn$_invoke$arity$2 ? datascript.core.q.cljs$core$IFn$_invoke$arity$2(G__39616,G__39617) : datascript.core.q.call(null,G__39616,G__39617));
})()));
return (entities.resources.data.interface$.example_resources.cljs$core$IFn$_invoke$arity$1 ? entities.resources.data.interface$.example_resources.cljs$core$IFn$_invoke$arity$1(G__39615) : entities.resources.data.interface$.example_resources.call(null,G__39615));
})());
var init_domain_entities = cljs.core.map.cljs$core$IFn$_invoke$arity$2(cljs.core.first,(function (){var G__39618 = new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"find","find",496279456),new cljs.core.Symbol(null,"?e","?e",-1194391683,null),new cljs.core.Keyword(null,"where","where",-2044795965),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Symbol(null,"?e","?e",-1194391683,null),new cljs.core.Keyword(null,"entity-type","entity-type",-1957300125),"domain"], null)], null);
var G__39619 = cljs.core.deref(conn);
return (datascript.core.q.cljs$core$IFn$_invoke$arity$2 ? datascript.core.q.cljs$core$IFn$_invoke$arity$2(G__39618,G__39619) : datascript.core.q.call(null,G__39618,G__39619));
})());
var init_resources = cljs.core.map.cljs$core$IFn$_invoke$arity$2(cljs.core.first,cljs.core.take.cljs$core$IFn$_invoke$arity$2((8),(function (){var G__39620 = new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"find","find",496279456),new cljs.core.Symbol(null,"?e","?e",-1194391683,null),new cljs.core.Keyword(null,"where","where",-2044795965),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Symbol(null,"?e","?e",-1194391683,null),new cljs.core.Keyword(null,"entity-type","entity-type",-1957300125),"resource"], null)], null);
var G__39621 = cljs.core.deref(conn);
return (datascript.core.q.cljs$core$IFn$_invoke$arity$2 ? datascript.core.q.cljs$core$IFn$_invoke$arity$2(G__39620,G__39621) : datascript.core.q.call(null,G__39620,G__39621));
})()));
var creature_resources = cljs.core.mapv.cljs$core$IFn$_invoke$arity$2((function (resource_id){
return new cljs.core.PersistentArrayMap(null, 3, [new cljs.core.Keyword(null,"entity-type","entity-type",-1957300125),"creature-resource",new cljs.core.Keyword("creature-resource","resource","creature-resource/resource",-3690952),resource_id,new cljs.core.Keyword("creature-resource","quantity","creature-resource/quantity",2108753046),(1)], null);
}),init_resources);
var ___$8 = datascript.core.transact_BANG_.cljs$core$IFn$_invoke$arity$2(conn,creature_resources);
var init_creature_resources = cljs.core.map.cljs$core$IFn$_invoke$arity$2(cljs.core.first,cljs.core.take.cljs$core$IFn$_invoke$arity$2((8),(function (){var G__39622 = new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"find","find",496279456),new cljs.core.Symbol(null,"?e","?e",-1194391683,null),new cljs.core.Keyword(null,"where","where",-2044795965),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Symbol(null,"?e","?e",-1194391683,null),new cljs.core.Keyword(null,"entity-type","entity-type",-1957300125),"creature-resource"], null)], null);
var G__39623 = cljs.core.deref(conn);
return (datascript.core.q.cljs$core$IFn$_invoke$arity$2 ? datascript.core.q.cljs$core$IFn$_invoke$arity$2(G__39622,G__39623) : datascript.core.q.call(null,G__39622,G__39623));
})()));
var ___$9 = cljs.core.println.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([(function (){var G__39624 = new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"find","find",496279456),new cljs.core.Symbol(null,"?e","?e",-1194391683,null),new cljs.core.Keyword(null,"where","where",-2044795965),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Symbol(null,"?e","?e",-1194391683,null),new cljs.core.Keyword("resource","quality-value","resource/quality-value",-1702050437),(3)], null)], null);
var G__39625 = cljs.core.deref(conn);
return (datascript.core.q.cljs$core$IFn$_invoke$arity$2 ? datascript.core.q.cljs$core$IFn$_invoke$arity$2(G__39624,G__39625) : datascript.core.q.call(null,G__39624,G__39625));
})()], 0));
var init_actions = cljs.core.map.cljs$core$IFn$_invoke$arity$2(cljs.core.first,(function (){var G__39626 = new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"find","find",496279456),new cljs.core.Symbol(null,"?e","?e",-1194391683,null),new cljs.core.Keyword(null,"where","where",-2044795965),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Symbol(null,"?e","?e",-1194391683,null),new cljs.core.Keyword(null,"entity-type","entity-type",-1957300125),"action"], null)], null);
var G__39627 = cljs.core.deref(conn);
return (datascript.core.q.cljs$core$IFn$_invoke$arity$2 ? datascript.core.q.cljs$core$IFn$_invoke$arity$2(G__39626,G__39627) : datascript.core.q.call(null,G__39626,G__39627));
})());
var ___$10 = datascript.core.transact_BANG_.cljs$core$IFn$_invoke$arity$2(conn,(entities.creatures.data.interface$.example_creatures.cljs$core$IFn$_invoke$arity$3 ? entities.creatures.data.interface$.example_creatures.cljs$core$IFn$_invoke$arity$3(init_domain_entities,init_creature_resources,init_actions) : entities.creatures.data.interface$.example_creatures.call(null,init_domain_entities,init_creature_resources,init_actions)));
var ___$11 = cljs.core.println.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([(function (){var G__39628 = new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"find","find",496279456),new cljs.core.Symbol(null,"?e","?e",-1194391683,null),new cljs.core.Keyword(null,"where","where",-2044795965),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Symbol(null,"?e","?e",-1194391683,null),new cljs.core.Keyword(null,"entity-type","entity-type",-1957300125),"creature"], null)], null);
var G__39629 = cljs.core.deref(conn);
return (datascript.core.q.cljs$core$IFn$_invoke$arity$2 ? datascript.core.q.cljs$core$IFn$_invoke$arity$2(G__39628,G__39629) : datascript.core.q.call(null,G__39628,G__39629));
})()], 0));
var ___$12 = datascript.core.transact_BANG_.cljs$core$IFn$_invoke$arity$2(conn,(function (){var G__39630 = cljs.core.vec(cljs.core.map.cljs$core$IFn$_invoke$arity$2(cljs.core.first,(function (){var G__39635 = new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"find","find",496279456),new cljs.core.Symbol(null,"?e","?e",-1194391683,null),new cljs.core.Keyword(null,"where","where",-2044795965),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Symbol(null,"?e","?e",-1194391683,null),new cljs.core.Keyword(null,"entity-type","entity-type",-1957300125),"realm"], null)], null);
var G__39636 = cljs.core.deref(conn);
return (datascript.core.q.cljs$core$IFn$_invoke$arity$2 ? datascript.core.q.cljs$core$IFn$_invoke$arity$2(G__39635,G__39636) : datascript.core.q.call(null,G__39635,G__39636));
})()));
var G__39631 = cljs.core.vec(cljs.core.map.cljs$core$IFn$_invoke$arity$2(cljs.core.first,(function (){var G__39637 = new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"find","find",496279456),new cljs.core.Symbol(null,"?e","?e",-1194391683,null),new cljs.core.Keyword(null,"where","where",-2044795965),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Symbol(null,"?e","?e",-1194391683,null),new cljs.core.Keyword(null,"entity-type","entity-type",-1957300125),"ruleset"], null)], null);
var G__39638 = cljs.core.deref(conn);
return (datascript.core.q.cljs$core$IFn$_invoke$arity$2 ? datascript.core.q.cljs$core$IFn$_invoke$arity$2(G__39637,G__39638) : datascript.core.q.call(null,G__39637,G__39638));
})()));
var G__39632 = cljs.core.vec(cljs.core.map.cljs$core$IFn$_invoke$arity$2(cljs.core.first,(function (){var G__39642 = new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"find","find",496279456),new cljs.core.Symbol(null,"?e","?e",-1194391683,null),new cljs.core.Keyword(null,"where","where",-2044795965),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Symbol(null,"?e","?e",-1194391683,null),new cljs.core.Keyword(null,"entity-type","entity-type",-1957300125),"creature"], null)], null);
var G__39643 = cljs.core.deref(conn);
return (datascript.core.q.cljs$core$IFn$_invoke$arity$2 ? datascript.core.q.cljs$core$IFn$_invoke$arity$2(G__39642,G__39643) : datascript.core.q.call(null,G__39642,G__39643));
})()));
var G__39633 = cljs.core.vec(cljs.core.map.cljs$core$IFn$_invoke$arity$2(cljs.core.first,(function (){var G__39647 = new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"find","find",496279456),new cljs.core.Symbol(null,"?e","?e",-1194391683,null),new cljs.core.Keyword(null,"where","where",-2044795965),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Symbol(null,"?e","?e",-1194391683,null),new cljs.core.Keyword(null,"entity-type","entity-type",-1957300125),"domain"], null)], null);
var G__39648 = cljs.core.deref(conn);
return (datascript.core.q.cljs$core$IFn$_invoke$arity$2 ? datascript.core.q.cljs$core$IFn$_invoke$arity$2(G__39647,G__39648) : datascript.core.q.call(null,G__39647,G__39648));
})()));
var G__39634 = cljs.core.vec(cljs.core.map.cljs$core$IFn$_invoke$arity$2(cljs.core.first,(function (){var G__39652 = new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"find","find",496279456),new cljs.core.Symbol(null,"?e","?e",-1194391683,null),new cljs.core.Keyword(null,"where","where",-2044795965),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Symbol(null,"?e","?e",-1194391683,null),new cljs.core.Keyword(null,"entity-type","entity-type",-1957300125),"resource"], null)], null);
var G__39653 = cljs.core.deref(conn);
return (datascript.core.q.cljs$core$IFn$_invoke$arity$2 ? datascript.core.q.cljs$core$IFn$_invoke$arity$2(G__39652,G__39653) : datascript.core.q.call(null,G__39652,G__39653));
})()));
return (entities.campaigns.data.interface$.init_campaigns.cljs$core$IFn$_invoke$arity$5 ? entities.campaigns.data.interface$.init_campaigns.cljs$core$IFn$_invoke$arity$5(G__39630,G__39631,G__39632,G__39633,G__39634) : entities.campaigns.data.interface$.init_campaigns.call(null,G__39630,G__39631,G__39632,G__39633,G__39634));
})());
return new cljs.core.Keyword(null,"success","success",1890645906);
});

//# sourceMappingURL=init.js.map
