goog.provide('init');
init.initialize_db = (function init$initialize_db(conn){
var _ = (function (){var G__31992 = conn;
var G__31993 = new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword("db","add","db/add",235286841),(1),new cljs.core.Keyword("navigator","history","navigator/history",744551073),new cljs.core.PersistentVector(null, 1, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.PersistentArrayMap(null, 1, [new cljs.core.Keyword(null,"page","page",849072397),new cljs.core.Keyword(null,"campaigns","campaigns",-1931854575)], null)], null)], null)], null);
return (datascript.core.transact_BANG_.cljs$core$IFn$_invoke$arity$2 ? datascript.core.transact_BANG_.cljs$core$IFn$_invoke$arity$2(G__31992,G__31993) : datascript.core.transact_BANG_.call(null,G__31992,G__31993));
})();
var ___$1 = (datascript.core.transact_BANG_.cljs$core$IFn$_invoke$arity$2 ? datascript.core.transact_BANG_.cljs$core$IFn$_invoke$arity$2(conn,entities.realms.data.interface$.example_realms) : datascript.core.transact_BANG_.call(null,conn,entities.realms.data.interface$.example_realms));
var ___$2 = (datascript.core.transact_BANG_.cljs$core$IFn$_invoke$arity$2 ? datascript.core.transact_BANG_.cljs$core$IFn$_invoke$arity$2(conn,entities.creatures.data.interface$.creature_races) : datascript.core.transact_BANG_.call(null,conn,entities.creatures.data.interface$.creature_races));
var ___$3 = (datascript.core.transact_BANG_.cljs$core$IFn$_invoke$arity$2 ? datascript.core.transact_BANG_.cljs$core$IFn$_invoke$arity$2(conn,entities.rulesets.data.interface$.default_domains) : datascript.core.transact_BANG_.call(null,conn,entities.rulesets.data.interface$.default_domains));
var ___$4 = (datascript.core.transact_BANG_.cljs$core$IFn$_invoke$arity$2 ? datascript.core.transact_BANG_.cljs$core$IFn$_invoke$arity$2(conn,entities.rulesets.data.interface$.example_rulesets) : datascript.core.transact_BANG_.call(null,conn,entities.rulesets.data.interface$.example_rulesets));
var ___$5 = (datascript.core.transact_BANG_.cljs$core$IFn$_invoke$arity$2 ? datascript.core.transact_BANG_.cljs$core$IFn$_invoke$arity$2(conn,entities.actions.data.interface$.example_actions) : datascript.core.transact_BANG_.call(null,conn,entities.actions.data.interface$.example_actions));
var ___$6 = (datascript.core.transact_BANG_.cljs$core$IFn$_invoke$arity$2 ? datascript.core.transact_BANG_.cljs$core$IFn$_invoke$arity$2(conn,entities.resources.data.interface$.resource_properties) : datascript.core.transact_BANG_.call(null,conn,entities.resources.data.interface$.resource_properties));
var ___$7 = (function (){var G__31998 = conn;
var G__31999 = (function (){var G__32000 = cljs.core.vec(cljs.core.map.cljs$core$IFn$_invoke$arity$2(cljs.core.first,(function (){var G__32001 = new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"find","find",496279456),new cljs.core.Symbol(null,"?e","?e",-1194391683,null),new cljs.core.Keyword(null,"where","where",-2044795965),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Symbol(null,"?e","?e",-1194391683,null),new cljs.core.Keyword(null,"entity-type","entity-type",-1957300125),"action"], null)], null);
var G__32002 = cljs.core.deref(conn);
return (datascript.core.q.cljs$core$IFn$_invoke$arity$2 ? datascript.core.q.cljs$core$IFn$_invoke$arity$2(G__32001,G__32002) : datascript.core.q.call(null,G__32001,G__32002));
})()));
return (entities.resources.data.interface$.example_resources.cljs$core$IFn$_invoke$arity$1 ? entities.resources.data.interface$.example_resources.cljs$core$IFn$_invoke$arity$1(G__32000) : entities.resources.data.interface$.example_resources.call(null,G__32000));
})();
return (datascript.core.transact_BANG_.cljs$core$IFn$_invoke$arity$2 ? datascript.core.transact_BANG_.cljs$core$IFn$_invoke$arity$2(G__31998,G__31999) : datascript.core.transact_BANG_.call(null,G__31998,G__31999));
})();
var init_domain_entities = cljs.core.map.cljs$core$IFn$_invoke$arity$2(cljs.core.first,(function (){var G__32005 = new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"find","find",496279456),new cljs.core.Symbol(null,"?e","?e",-1194391683,null),new cljs.core.Keyword(null,"where","where",-2044795965),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Symbol(null,"?e","?e",-1194391683,null),new cljs.core.Keyword(null,"entity-type","entity-type",-1957300125),"domain"], null)], null);
var G__32006 = cljs.core.deref(conn);
return (datascript.core.q.cljs$core$IFn$_invoke$arity$2 ? datascript.core.q.cljs$core$IFn$_invoke$arity$2(G__32005,G__32006) : datascript.core.q.call(null,G__32005,G__32006));
})());
var init_resources = cljs.core.map.cljs$core$IFn$_invoke$arity$2(cljs.core.first,cljs.core.take.cljs$core$IFn$_invoke$arity$2((8),(function (){var G__32010 = new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"find","find",496279456),new cljs.core.Symbol(null,"?e","?e",-1194391683,null),new cljs.core.Keyword(null,"where","where",-2044795965),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Symbol(null,"?e","?e",-1194391683,null),new cljs.core.Keyword(null,"entity-type","entity-type",-1957300125),"resource"], null)], null);
var G__32011 = cljs.core.deref(conn);
return (datascript.core.q.cljs$core$IFn$_invoke$arity$2 ? datascript.core.q.cljs$core$IFn$_invoke$arity$2(G__32010,G__32011) : datascript.core.q.call(null,G__32010,G__32011));
})()));
var creature_resources = cljs.core.mapv.cljs$core$IFn$_invoke$arity$2((function (resource_id){
return new cljs.core.PersistentArrayMap(null, 3, [new cljs.core.Keyword(null,"entity-type","entity-type",-1957300125),"creature-resource",new cljs.core.Keyword("creature-resource","resource","creature-resource/resource",-3690952),resource_id,new cljs.core.Keyword("creature-resource","quantity","creature-resource/quantity",2108753046),(1)], null);
}),init_resources);
var ___$8 = (datascript.core.transact_BANG_.cljs$core$IFn$_invoke$arity$2 ? datascript.core.transact_BANG_.cljs$core$IFn$_invoke$arity$2(conn,creature_resources) : datascript.core.transact_BANG_.call(null,conn,creature_resources));
var init_creature_resources = cljs.core.map.cljs$core$IFn$_invoke$arity$2(cljs.core.first,cljs.core.take.cljs$core$IFn$_invoke$arity$2((8),(function (){var G__32015 = new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"find","find",496279456),new cljs.core.Symbol(null,"?e","?e",-1194391683,null),new cljs.core.Keyword(null,"where","where",-2044795965),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Symbol(null,"?e","?e",-1194391683,null),new cljs.core.Keyword(null,"entity-type","entity-type",-1957300125),"creature-resource"], null)], null);
var G__32016 = cljs.core.deref(conn);
return (datascript.core.q.cljs$core$IFn$_invoke$arity$2 ? datascript.core.q.cljs$core$IFn$_invoke$arity$2(G__32015,G__32016) : datascript.core.q.call(null,G__32015,G__32016));
})()));
var ___$9 = cljs.core.println.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([(function (){var G__32017 = new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"find","find",496279456),new cljs.core.Symbol(null,"?e","?e",-1194391683,null),new cljs.core.Keyword(null,"where","where",-2044795965),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Symbol(null,"?e","?e",-1194391683,null),new cljs.core.Keyword("resource","quality-value","resource/quality-value",-1702050437),(3)], null)], null);
var G__32018 = cljs.core.deref(conn);
return (datascript.core.q.cljs$core$IFn$_invoke$arity$2 ? datascript.core.q.cljs$core$IFn$_invoke$arity$2(G__32017,G__32018) : datascript.core.q.call(null,G__32017,G__32018));
})()], 0));
var init_actions = cljs.core.map.cljs$core$IFn$_invoke$arity$2(cljs.core.first,(function (){var G__32019 = new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"find","find",496279456),new cljs.core.Symbol(null,"?e","?e",-1194391683,null),new cljs.core.Keyword(null,"where","where",-2044795965),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Symbol(null,"?e","?e",-1194391683,null),new cljs.core.Keyword(null,"entity-type","entity-type",-1957300125),"action"], null)], null);
var G__32020 = cljs.core.deref(conn);
return (datascript.core.q.cljs$core$IFn$_invoke$arity$2 ? datascript.core.q.cljs$core$IFn$_invoke$arity$2(G__32019,G__32020) : datascript.core.q.call(null,G__32019,G__32020));
})());
var ___$10 = (function (){var G__32025 = conn;
var G__32026 = (entities.creatures.data.interface$.example_creatures.cljs$core$IFn$_invoke$arity$3 ? entities.creatures.data.interface$.example_creatures.cljs$core$IFn$_invoke$arity$3(init_domain_entities,init_creature_resources,init_actions) : entities.creatures.data.interface$.example_creatures.call(null,init_domain_entities,init_creature_resources,init_actions));
return (datascript.core.transact_BANG_.cljs$core$IFn$_invoke$arity$2 ? datascript.core.transact_BANG_.cljs$core$IFn$_invoke$arity$2(G__32025,G__32026) : datascript.core.transact_BANG_.call(null,G__32025,G__32026));
})();
var ___$11 = cljs.core.println.cljs$core$IFn$_invoke$arity$variadic(cljs.core.prim_seq.cljs$core$IFn$_invoke$arity$2([(function (){var G__32028 = new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"find","find",496279456),new cljs.core.Symbol(null,"?e","?e",-1194391683,null),new cljs.core.Keyword(null,"where","where",-2044795965),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Symbol(null,"?e","?e",-1194391683,null),new cljs.core.Keyword(null,"entity-type","entity-type",-1957300125),"creature"], null)], null);
var G__32029 = cljs.core.deref(conn);
return (datascript.core.q.cljs$core$IFn$_invoke$arity$2 ? datascript.core.q.cljs$core$IFn$_invoke$arity$2(G__32028,G__32029) : datascript.core.q.call(null,G__32028,G__32029));
})()], 0));
var ___$12 = (function (){var G__32030 = conn;
var G__32031 = (function (){var G__32032 = cljs.core.vec(cljs.core.map.cljs$core$IFn$_invoke$arity$2(cljs.core.first,(function (){var G__32037 = new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"find","find",496279456),new cljs.core.Symbol(null,"?e","?e",-1194391683,null),new cljs.core.Keyword(null,"where","where",-2044795965),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Symbol(null,"?e","?e",-1194391683,null),new cljs.core.Keyword(null,"entity-type","entity-type",-1957300125),"realm"], null)], null);
var G__32038 = cljs.core.deref(conn);
return (datascript.core.q.cljs$core$IFn$_invoke$arity$2 ? datascript.core.q.cljs$core$IFn$_invoke$arity$2(G__32037,G__32038) : datascript.core.q.call(null,G__32037,G__32038));
})()));
var G__32033 = cljs.core.vec(cljs.core.map.cljs$core$IFn$_invoke$arity$2(cljs.core.first,(function (){var G__32039 = new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"find","find",496279456),new cljs.core.Symbol(null,"?e","?e",-1194391683,null),new cljs.core.Keyword(null,"where","where",-2044795965),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Symbol(null,"?e","?e",-1194391683,null),new cljs.core.Keyword(null,"entity-type","entity-type",-1957300125),"ruleset"], null)], null);
var G__32040 = cljs.core.deref(conn);
return (datascript.core.q.cljs$core$IFn$_invoke$arity$2 ? datascript.core.q.cljs$core$IFn$_invoke$arity$2(G__32039,G__32040) : datascript.core.q.call(null,G__32039,G__32040));
})()));
var G__32034 = cljs.core.vec(cljs.core.map.cljs$core$IFn$_invoke$arity$2(cljs.core.first,(function (){var G__32041 = new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"find","find",496279456),new cljs.core.Symbol(null,"?e","?e",-1194391683,null),new cljs.core.Keyword(null,"where","where",-2044795965),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Symbol(null,"?e","?e",-1194391683,null),new cljs.core.Keyword(null,"entity-type","entity-type",-1957300125),"creature"], null)], null);
var G__32042 = cljs.core.deref(conn);
return (datascript.core.q.cljs$core$IFn$_invoke$arity$2 ? datascript.core.q.cljs$core$IFn$_invoke$arity$2(G__32041,G__32042) : datascript.core.q.call(null,G__32041,G__32042));
})()));
var G__32035 = cljs.core.vec(cljs.core.map.cljs$core$IFn$_invoke$arity$2(cljs.core.first,(function (){var G__32043 = new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"find","find",496279456),new cljs.core.Symbol(null,"?e","?e",-1194391683,null),new cljs.core.Keyword(null,"where","where",-2044795965),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Symbol(null,"?e","?e",-1194391683,null),new cljs.core.Keyword(null,"entity-type","entity-type",-1957300125),"domain"], null)], null);
var G__32044 = cljs.core.deref(conn);
return (datascript.core.q.cljs$core$IFn$_invoke$arity$2 ? datascript.core.q.cljs$core$IFn$_invoke$arity$2(G__32043,G__32044) : datascript.core.q.call(null,G__32043,G__32044));
})()));
var G__32036 = cljs.core.vec(cljs.core.map.cljs$core$IFn$_invoke$arity$2(cljs.core.first,(function (){var G__32045 = new cljs.core.PersistentVector(null, 4, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Keyword(null,"find","find",496279456),new cljs.core.Symbol(null,"?e","?e",-1194391683,null),new cljs.core.Keyword(null,"where","where",-2044795965),new cljs.core.PersistentVector(null, 3, 5, cljs.core.PersistentVector.EMPTY_NODE, [new cljs.core.Symbol(null,"?e","?e",-1194391683,null),new cljs.core.Keyword(null,"entity-type","entity-type",-1957300125),"resource"], null)], null);
var G__32046 = cljs.core.deref(conn);
return (datascript.core.q.cljs$core$IFn$_invoke$arity$2 ? datascript.core.q.cljs$core$IFn$_invoke$arity$2(G__32045,G__32046) : datascript.core.q.call(null,G__32045,G__32046));
})()));
return (entities.campaigns.data.interface$.init_campaigns.cljs$core$IFn$_invoke$arity$5 ? entities.campaigns.data.interface$.init_campaigns.cljs$core$IFn$_invoke$arity$5(G__32032,G__32033,G__32034,G__32035,G__32036) : entities.campaigns.data.interface$.init_campaigns.call(null,G__32032,G__32033,G__32034,G__32035,G__32036));
})();
return (datascript.core.transact_BANG_.cljs$core$IFn$_invoke$arity$2 ? datascript.core.transact_BANG_.cljs$core$IFn$_invoke$arity$2(G__32030,G__32031) : datascript.core.transact_BANG_.call(null,G__32030,G__32031));
})();
return new cljs.core.Keyword(null,"success","success",1890645906);
});

//# sourceMappingURL=init.js.map
